title: (재)일본군성노예제문제해결을위한정의기억연대
baseURL: https://stage.womenandwar.net

defaultContentLanguage: ko
hasCJKLanguage: true
paginate: 12

build:
  writeStats: true

googleAnalytics:

taxonomies:
  tag: tags
  category: categories