backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'slides'
    label: '메인 슬라이드'
    folder: 'content/slides'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '순서', name: 'weight', widget: 'string' }    
      - { label: '상단메세지', name: 'upper_message', widget: 'string', required: false }
      - { label: '제목', name: 'title', widget: 'string', required: false }
      - { label: '부제목', name: 'sub_title', widget: 'string', required: false }
      - { label: '날짜', name: 'date', widget: 'datetime', required: false } 
      - { label: "슬라이드 배경이미지", name: "image", widget: "image" }
      - { label: '버튼제목', name: 'button_name', widget: 'string', required: false }
      - { label: '버튼URL', name: 'button_url', widget: 'string', required: false }
  - name: 'notice'
    label: '공지사항'
    folder: 'content/connect/notice'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - label: "첨부파일"
        name: "post_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - label: "분류"
        name: "categories"
        widget: "select"
        multiple: true
        options: [ "공지", "보도자료", "문서" ]
        default: ["공지"]
        hint: '공지 / 보도자료 / 문서'              
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '목록 고정', name: 'pinned', widget: 'boolean', default: false, hint: 'true 목록고정', required: false }
  - name: 'post'
    label: '활동(post)'
    folder: 'content/actions/post'
    create: true
    slug: '{{slug}}' 
    editor:
      preview: true
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }      
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - label: "첨부파일"
        name: "post_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - label: "분류"
        name: "categories"
        widget: "select"
        multiple: true
        options: [ "this-week", "연대사업", "video", "생존자복지", "연구조사교육", "전시성폭력재발방지", "기림사업", "나비기금", "donation", "쉼터소식", "일본국상대소송", "japanese", "장학사업", "후원스토리" ]
        default: [ "this-week" ]
        hint: 'this-week 수요시위'              
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '목록 고정', name: 'pinned', widget: 'boolean', default: false, hint: 'true 목록고정', required: false }
  - name: 'budget'
    label: '살림살이'
    folder: 'content/about/budget'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - label: "첨부파일"
        name: "post_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true      
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '목록 고정', name: 'pinned', widget: 'boolean', default: false, hint: 'true 목록고정', required: false }      